### ISSUE TITLE
documentation and pretrained models

### ISSUE THREAD

**Issue by seekingdeep** [skgusrb12/voice_activity_detection#1]
@skgusrb12 
it would be better if you
- add documentation on how to prepare, train, and predict.
- add the pretrained models so that we can test

**Comment by skgusrb12** [comment]
Thank you for your comment.

**Comment by seekingdeep** [comment]
How does your code compares with [Nvidia's nemo](https://github.com/NVIDIA/NeMo/blob/main/tutorials/asr/06_Voice_Activiy_Detection.ipynb) accuracy and performance?
https://arxiv.org/pdf/2004.08531.pdf

Thanks

**Comment by skgusrb12** [comment]
Thank you for your good opinion. First of all, we just utilized this project to participate in the AI grand challenge. So, we did not compare with other methods. I appreciate your opinion in this respect. I will update our project using Nvidia's nemo.

**Comment by skgusrb12** [comment]
> How does your code compares with [Nvidia's nemo](https://github.com/NVIDIA/NeMo/blob/main/tutorials/asr/06_Voice_Activiy_Detection.ipynb) accuracy and performance?
> https://arxiv.org/pdf/2004.08531.pdf
> 
> Thanks

Thank you for your good opinion. First of all, we just utilized this project to participate in the AI grand challenge. So, we did not compare with other methods. I appreciate your opinion in this respect. I will update our project using Nvidia's nemo.
